# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UI
  pod 'SnapKit', '~> 5.6.0'
  pod 'Then'
  pod 'EasyTipView', '~> 2.1'

end
